# Generated by Django 4.1.5 on 2023-01-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_options_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleados', verbose_name='Imagen'),
        ),
    ]
