# Generated by Django 4.1.5 on 2023-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('Contador', 'Contador'), ('Administrador', 'Administrador'), ('Economista', 'Economista'), ('Otro', 'Otro')], max_length=30, verbose_name='Puesto'),
        ),
    ]
